site_name: My Epic Campaign Wiki
site_url: https://gitbrry.github.io/Campaign-Wiki/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.expand # This forces all folders to stay "open" so you see sub-items
    # DO NOT add navigation.tabs here - it will break the sidebar!

docs_dir: 'docs'

plugins:
  - search
  - roamlinks

nav:
  - Home: index.md
  - World Graph: World_Graph.md
  - Locations: 
    - Overview: 02_Locations/index.md
    - 02_Locations/ # This tells it to look for everything else in the folder
  - NPCs:
    - Overview: 03_NPCs/index.md
    - 03_NPCs/
  - Lore:
    - Overview: 04_Lore_and_Factions/index.md
    - 04_Lore_and_Factions/
  - Session Summaries:
    - Overview: 05_Session_Summaries/index.md
    - 05_Session_Summaries/