site_name: My Epic Campaign Wiki
site_url: https://gitbrry.github.io/Campaign-Wiki/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes # Essential for merging index files
    # No sections, no expand, no tabs. 

docs_dir: 'docs'

plugins:
  - search
  - roamlinks
  - awesome-pages:
      collapse_single_pages: true # New setting: hides folders that only have 1 page

# We are leaving the nav out so awesome-pages can handle the logic