site_name: My Epic Campaign Wiki
site_url: https://gitbrry.github.io/Campaign-Wiki/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes # This merges the folder name with the index file
    - navigation.prune   # This is the secret! It "prunes" (hides) things you aren't looking at
    # navigation.sections is REMOVED
    # navigation.expand is REMOVED

docs_dir: 'docs'

plugins:
  - search
  - roamlinks
  - awesome-pages