site_name: My Epic Campaign Wiki
site_url: https://gitbrry.github.io/Campaign-Wiki/
# We REMOVED use_directory_urls: false to allow the links to merge

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.sections # Gives you the bold headers
    - navigation.indexes  # MERGES the index file into the bold header
    - navigation.expand   # Keeps the sub-items visible

docs_dir: 'docs'

plugins:
  - search
  - roamlinks
  - awesome-pages