site_name: My Epic Campaign Wiki
site_url: https://gitbrry.github.io/Campaign-Wiki/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes # Essential for clicking the folder name itself

docs_dir: 'docs'

plugins:
  - search
  - roamlinks
  - awesome-pages:
      collapse_single_pages: true