site_name: My Epic Campaign Wiki
site_url: https://gitbrry.github.io/Campaign-Wiki/
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.expand # This makes sub-menus stay open/expand nicely
    - navigation.tabs # Optional: Adds a top bar for main categories
    - navigation.sections # Groups items into clear sections

docs_dir: 'docs'

plugins:
  - search
  - roamlinks

nav:
  - Home: index.md
  - World Graph: World_Graph.md
  - Locations: 02_Locations/
  - NPCs: 03_NPCs/
  - Lore: 04_Lore_and_Factions/
  - Session Summaries: 05_Session_Summaries/