site_name: My Epic Campaign Wiki
site_url: https://gitbrry.github.io/Campaign-Wiki/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes # This merges the folder name with the index file
    # navigation.sections - REMOVED (This was forcing them to stay open and bold)
    # navigation.expand - REMOVED (This was forcing sub-items to stay visible)

docs_dir: 'docs'

plugins:
  - search
  - roamlinks
  - awesome-pages