site_name: My Epic Campaign Wiki
site_url: https://gitbrry.github.io/Campaign-Wiki/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes # Merges the folder name with the index.md file
    - navigation.sections # Makes the folder names bold
    # We REMOVED navigation.expand so the menu stays collapsed
    # We REMOVED use_directory_urls: false to fix the page breaking

docs_dir: 'docs'

plugins:
  - search
  - roamlinks
  - awesome-pages