site_name: My Epic Campaign Wiki
site_url: https://gitbrry.github.io/Campaign-Wiki/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes # Merges the folder with the index file
    - navigation.sections # Ensures arrows and bold headers stay consistent
    # navigation.expand is GONE (to keep it collapsed)

docs_dir: 'docs'

plugins:
  - search
  - roamlinks
  - awesome-pages